Preprocessing time: 0.002741098403930664
sigma=1,epsilon=20
k_range (1, 14)
k:  1
k:  2
k:  3
k:  4
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
k:  5
k:  6
Process Process-4:
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
k:  7
k:  8
k:  9
k:  10
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
k:  11
k:  12
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
k:  13
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Process Process-13:
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
k:  14
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 141, in get_mean_squared_error_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 257, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 32, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 45, in find_k_nearest_neighbors
    distance = -1 * self.distance_function.compute_distance(
AttributeError: 'int' object has no attribute 'compute_distance'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 385, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/braeden/Git/csci447-project-01/Project02/main.py", line 187, in <module>
    run_computer_hardware_expirement()
  File "/home/braeden/Git/csci447-project-01/Project02/main.py", line 179, in run_computer_hardware_expirement
    tuned_params_eknn = tuning_utility.tune_sigma_k_and_epsilon_for_folds(training_test_data, tuning_data, [1, 20], 1, [20, 50], 5);
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 25, in tune_sigma_k_and_epsilon_for_folds
    best_results = self.tune_k_for_folds(training_test_data, tuning_data, model_params=[sigma, epsilon])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 64, in tune_k_for_folds
    k, measure = results_df.loc[0]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 3864, in xs
    loc = index.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 387, in get_loc
    raise KeyError(key) from err
KeyError: 0
